"""Executive Business Report Generation Service.

Compiles comprehensive, professional analytical reports in HTML, Markdown, and text formats.
Suitable for executive presentation and technical portfolios.
"""

import datetime
import json


def generate_executive_report(dataset_dict, profile, insights_data, anomalies_data, correlations_data, ai_narrative=None):
    """
    Synthesize all analytical dimensions into an executive-ready business report.
    Returns:
        - html_report: Styled standalone HTML document with CSS and responsive layout
        - markdown_report: Clean GitHub-flavored markdown document
    """
    now_str = datetime.datetime.now().strftime("%B %d, %Y at %I:%M %p")
    filename = dataset_dict.get("original_filename") or dataset_dict.get("filename", "Dataset")
    health_score = dataset_dict.get("health_score", 0)

    # 1. Overview metrics
    overview = profile.get("overview", {})
    quality = profile.get("quality", {})
    kpis = insights_data.get("kpis", [])
    deterministic_insights = insights_data.get("insights", [])
    highlights = insights_data.get("executive_highlights", [])
    
    anom_count = anomalies_data.get("total_anomalies", 0)
    anom_pct = anomalies_data.get("total_percentage", 0)
    top_pos_corr = correlations_data.get("top_positive", [])[:3]
    top_neg_corr = correlations_data.get("top_negative", [])[:3]

    # Markdown Report Generation
    md_lines = []
    md_lines.append(f"# Executive Analytical Report: {filename}")
    md_lines.append(f"**Generated by Data Analyst Agent** | *{now_str}*\n")
    md_lines.append("---")
    
    md_lines.append("## 1. Executive Summary")
    if ai_narrative and ai_narrative.get("executive_summary"):
        md_lines.append(ai_narrative["executive_summary"] + "\n")
    else:
        md_lines.append(f"This report presents an automated, quantitative evaluation of `{filename}` containing {overview.get('rows', 0):,} records across {overview.get('columns', 0)} attributes. Overall data health is evaluated at **{health_score}/100**.")
        if highlights:
            md_lines.append("\n**Key Takeaways:**")
            for h in highlights:
                md_lines.append(f"- {h}")
        md_lines.append("")

    md_lines.append("## 2. Key Performance Indicators")
    if kpis:
        for k in kpis:
            md_lines.append(f"- **{k['title']}**: {k['value']} *({k.get('subtitle', '')})*")
        md_lines.append("")
    else:
        md_lines.append("No direct financial or volume KPIs detected for this dataset structure.\n")

    md_lines.append("## 3. Data Quality & Health Assessment")
    md_lines.append(f"- **Data Health Score**: {health_score}/100")
    md_lines.append(f"- **Total Records**: {overview.get('rows', 0):,}")
    md_lines.append(f"- **Missing Value Cells**: {quality.get('total_missing', 0):,} ({quality.get('missing_percentage', 0)}%)")
    md_lines.append(f"- **Duplicate Rows**: {quality.get('duplicate_rows', 0):,} ({quality.get('duplicate_percentage', 0)}%)")
    md_lines.append(f"- **Completely Clean Rows**: {quality.get('complete_rows', 0):,} ({quality.get('complete_percentage', 0)}%)\n")

    md_lines.append("## 4. Business Insights & Trends")
    if deterministic_insights:
        for ins in deterministic_insights:
            md_lines.append(f"### {ins['category']}: {ins['headline']}")
            md_lines.append(f"{ins['details']}\n")
    else:
        md_lines.append("No critical distribution anomalies or concentration patterns flagged.\n")

    md_lines.append("## 5. Statistical Anomaly Detection")
    md_lines.append(f"- **Method Used**: {anomalies_data.get('method', 'IQR')}")
    md_lines.append(f"- **Total Potential Anomalies**: {anom_count:,} ({anom_pct}% of dataset)")
    if anomalies_data.get("column_details"):
        md_lines.append("\n**Affected Metrics Breakdown:**")
        for cd in anomalies_data["column_details"]:
            md_lines.append(f"- Column `{cd['column']}`: {cd['count']} outlier values outside normal range [{cd.get('lower_bound')}, {cd.get('upper_bound')}].")
    md_lines.append("")

    md_lines.append("## 6. Correlation Analysis")
    if top_pos_corr:
        md_lines.append("**Strongest Positive Associations:**")
        for pc in top_pos_corr:
            md_lines.append(f"- `{pc['column_1']}` & `{pc['column_2']}`: r = {pc['correlation']} ({pc['strength']})")
    if top_neg_corr:
        md_lines.append("\n**Strongest Inverse Associations:**")
        for nc in top_neg_corr:
            md_lines.append(f"- `{nc['column_1']}` & `{nc['column_2']}`: r = {nc['correlation']} ({nc['strength']})")
    md_lines.append(f"\n*Statistical Notice: {correlations_data.get('disclaimer', '')}*\n")

    md_lines.append("## 7. Strategic Recommendations")
    if ai_narrative and ai_narrative.get("recommendations"):
        for rec in ai_narrative["recommendations"]:
            md_lines.append(f"- {rec}")
    else:
        md_lines.append("1. **Address Missing Values**: Review columns with missing entries prior to operational deployment.")
        md_lines.append("2. **Investigate Outliers**: Validate whether statistical anomalies reflect high-value transactions or data entry inaccuracies.")
        md_lines.append("3. **Capitalize on Dominant Segments**: Focus commercial optimization around top contributing categories highlighted in Section 4.")
    md_lines.append("\n---")
    md_lines.append("### Methodology & Governance")
    md_lines.append("All calculations performed using pure deterministic algorithms in Python (NumPy, SciPy, Pandas). Health scoring adheres to the 5-pillar completeness, uniqueness, consistency, validity, and timeliness rubric.")

    markdown_report = "\n".join(md_lines)

    # Generate Professional Self-Contained HTML
    html_report = _build_html_report(filename, now_str, health_score, overview, quality, kpis, deterministic_insights, anomalies_data, correlations_data, ai_narrative)

    return {
        "markdown": markdown_report,
        "html": html_report
    }


def _build_html_report(filename, now_str, health_score, overview, quality, kpis, insights, anomalies_data, correlations_data, ai_narrative):
    """Build a standalone, beautifully styled HTML document."""
    kpi_cards_html = ""
    for k in kpis:
        kpi_cards_html += f"""
        <div class="kpi-card">
            <div class="kpi-title">{k['title']}</div>
            <div class="kpi-val">{k['value']}</div>
            <div class="kpi-sub">{k.get('subtitle', '')}</div>
        </div>
        """

    insights_html = ""
    for ins in insights:
        insights_html += f"""
        <div class="insight-item">
            <div class="badge">{ins['category']}</div>
            <h4>{ins['headline']}</h4>
            <p>{ins['details']}</p>
        </div>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AnalystFlow AI Executive Report - {filename}</title>
    <style>
        :root {{
            --bg: #0f172a;
            --surface: #1e293b;
            --surface-border: #334155;
            --text-main: #f8fafc;
            --text-muted: #94a3b8;
            --primary: #6366f1;
            --success: #10b981;
            --warning: #f59e0b;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background-color: var(--bg);
            color: var(--text-main);
            margin: 0;
            padding: 40px 20px;
            line-height: 1.6;
        }}
        .report-container {{
            max-width: 900px;
            margin: 0 auto;
            background: var(--surface);
            padding: 48px;
            border-radius: 16px;
            border: 1px solid var(--surface-border);
            box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5);
        }}
        .header {{
            border-bottom: 1px solid var(--surface-border);
            padding-bottom: 24px;
            margin-bottom: 32px;
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
        }}
        .brand {{
            font-size: 14px;
            font-weight: 700;
            color: var(--primary);
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 8px;
        }}
        h1 {{
            margin: 0 0 8px 0;
            font-size: 28px;
            color: #ffffff;
        }}
        .date {{
            color: var(--text-muted);
            font-size: 14px;
        }}
        .health-badge {{
            background: rgba(16, 185, 129, 0.15);
            border: 1px solid var(--success);
            color: var(--success);
            padding: 8px 16px;
            border-radius: 9999px;
            font-weight: 700;
            font-size: 16px;
            text-align: center;
        }}
        h2 {{
            color: #ffffff;
            border-bottom: 1px solid var(--surface-border);
            padding-bottom: 8px;
            margin-top: 36px;
            font-size: 20px;
        }}
        .kpi-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 16px;
            margin: 20px 0;
        }}
        .kpi-card {{
            background: #0f172a;
            padding: 20px;
            border-radius: 10px;
            border: 1px solid var(--surface-border);
        }}
        .kpi-title {{ font-size: 12px; color: var(--text-muted); text-transform: uppercase; font-weight: 600; }}
        .kpi-val {{ font-size: 24px; font-weight: 700; color: #ffffff; margin: 6px 0; }}
        .kpi-sub {{ font-size: 12px; color: var(--text-muted); }}
        .insight-item {{
            background: rgba(255, 255, 255, 0.02);
            border: 1px solid var(--surface-border);
            border-left: 4px solid var(--primary);
            padding: 18px;
            border-radius: 8px;
            margin-bottom: 14px;
        }}
        .badge {{
            display: inline-block;
            font-size: 11px;
            background: rgba(99, 102, 241, 0.2);
            color: var(--primary);
            padding: 2px 8px;
            border-radius: 4px;
            font-weight: 600;
            margin-bottom: 6px;
        }}
        .insight-item h4 {{ margin: 0 0 6px 0; font-size: 16px; color: #ffffff; }}
        .insight-item p {{ margin: 0; color: var(--text-muted); font-size: 14px; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 16px 0;
        }}
        th, td {{
            text-align: left;
            padding: 10px 14px;
            border-bottom: 1px solid var(--surface-border);
            font-size: 14px;
        }}
        th {{ color: var(--text-muted); font-weight: 600; }}
        .footer {{
            margin-top: 48px;
            border-top: 1px solid var(--surface-border);
            padding-top: 20px;
            font-size: 12px;
            color: var(--text-muted);
            display: flex;
            justify-content: space-between;
        }}
    </style>
</head>
<body>
    <div class="report-container">
        <div class="header">
            <div>
                <div class="brand">Data Analyst Agent &bull; Executive Intelligence</div>
                <h1>{filename}</h1>
                <div class="date">Generated {now_str}</div>
            </div>
            <div class="health-badge">
                Data Health: {health_score}/100
            </div>
        </div>

        <h2>Key Performance Indicators</h2>
        <div class="kpi-grid">
            {kpi_cards_html}
        </div>

        <h2>Data Quality Profile</h2>
        <table>
            <tr><th>Metric</th><th>Observed Value</th><th>Status</th></tr>
            <tr><td>Total Processed Records</td><td>{overview.get('rows', 0):,}</td><td>Complete</td></tr>
            <tr><td>Total Attributes (Columns)</td><td>{overview.get('columns', 0)}</td><td>Verified</td></tr>
            <tr><td>Missing Data Cells</td><td>{quality.get('total_missing', 0):,} ({quality.get('missing_percentage', 0)}%)</td><td>{'Normal' if quality.get('missing_percentage', 0) < 5 else 'Attention Needed'}</td></tr>
            <tr><td>Duplicate Rows</td><td>{quality.get('duplicate_rows', 0):,} ({quality.get('duplicate_percentage', 0)}%)</td><td>{'Clean' if quality.get('duplicate_rows', 0) == 0 else 'Deduplication Suggested'}</td></tr>
        </table>

        <h2>Business Insights & Discoveries</h2>
        <div>
            {insights_html if insights_html else '<p style="color:var(--text-muted)">All observed distributions are within typical variance thresholds.</p>'}
        </div>

        <h2>Anomaly & Outlier Surveillance</h2>
        <p>Total potential statistical anomalies detected: <strong>{anomalies_data.get('total_anomalies', 0):,}</strong> ({anomalies_data.get('total_percentage', 0)}% of records).</p>

        <h2>Strategic Recommendations</h2>
        <ol>
            <li><strong>Data Cleanliness:</strong> Systematically isolate entries with null values in core business dimensions.</li>
            <li><strong>Margin & Revenue Protection:</strong> Audit outlier transactions for accuracy and address segment-specific churn.</li>
            <li><strong>Focused Execution:</strong> Allocate strategic investment toward top revenue-generating products and regions.</li>
        </ol>

        <div class="footer">
            <span>Data Analyst Agent Analytics Engine</span>
            <span>Deterministic Analysis &bull; Pure Python Verification</span>
        </div>
    </div>
</body>
</html>
"""
