"""Google Gemini LLM Provider implementation using pure HTTP."""

import json
import urllib.request
import urllib.error
from ai.provider import LLMProvider


class GeminiProvider(LLMProvider):
    def __init__(self, api_key: str = "", model: str = "gemini-1.5-flash"):
        self.api_key = api_key
        self.model = model or "gemini-1.5-flash"

    def is_configured(self) -> bool:
        return bool(self.api_key and len(self.api_key.strip()) > 5)

    def generate_text(self, prompt: str, system_prompt: str = "") -> str:
        if not self.is_configured():
            return "AI key not configured. Running in local deterministic analytics mode."

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"
        headers = {
            "Content-Type": "application/json"
        }

        full_prompt = f"{system_prompt}\n\nUser Request:\n{prompt}" if system_prompt else prompt

        payload = {
            "contents": [
                {
                    "parts": [{"text": full_prompt}]
                }
            ],
            "generationConfig": {
                "temperature": 0.2
            }
        }

        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers=headers,
                method="POST"
            )
            with urllib.request.urlopen(req, timeout=30) as response:
                result = json.loads(response.read().decode("utf-8"))
                candidates = result.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        return parts[0].get("text", "")
                return "No response content generated by Gemini."
        except urllib.error.HTTPError as e:
            err_body = e.read().decode("utf-8", errors="ignore")
            return f"Gemini API Error ({e.code}): {err_body[:200]}"
        except Exception as e:
            return f"Gemini Generation Failed: {str(e)[:200]}"
